[options]

db_host = localhost
db_user = odoouser
db_password = odoo123
db_name = odoodata
xmlrpc_port = 8069
without_demo = all
addons_path = odoo/addons,addons,accounting_kit,muk_theme,myaddons
admin_passwd = $pbkdf2-sha512$6000000$yVar9f4/xzgHAKD0kPIeQSoY7QrfLXdWd6VMlfd9Z0gcaqIDK6NxiTneOU7D4KqG2LdsIyc0Z8Wb5f0Ib/uemOWZ.DANsHt5Yg.sPNnVhJg
